// Public surface of src/config (ported from internal/config).

export { ProjectDirName, projectPath, projectPathFor } from "./paths.ts";
export {
  type ApprovalSettings,
  attachmentStorageReclaimSchedule,
  BoolPtr,
  cloneBoolPtr,
  cloneFloat64Ptr,
  cloneStringMap,
  cloneStringSlice,
  type CompactionSettings,
  configDir,
  type ContextFilesSettings,
  defaultModelConfig,
  defaultProviderConfig,
  defaultProviderConfigsAll,
  defaultSettings,
  DefaultSkillHubOfficialHandle,
  DefaultToolExecutionMaxConcurrency,
  effectiveImageGeneration,
  getGlobalSkillsDir,
  getModelConfig,
  getProviderConfig,
  getSessionDir,
  getShell,
  globalSettingsPath,
  type ImageGenerationSettings,
  isACPArtifactEnabled,
  isArtifactEnabled,
  isAttachmentStorageReclaimEnabled,
  isImageGenerationEnabled,
  isPlanToolEnabled,
  isProjectDir,
  isUpdateCheckEnabled,
  isWebSearchEnabled,
  loadGlobalSettingsOrDefault,
  loadGlobalSettingsSparse,
  type LoadMeta,
  loadProjectSettingsSparse,
  loadSettings,
  loadSettingsFor,
  loadSettingsWithMeta,
  type MaintenanceSettings,
  marshalSettings,
  mergeModelConfig,
  mergeModelConfigs,
  mergeProviderConfig,
  mergeWebSearchSettings,
  type ModelCompat,
  type ModelConfig,
  modelMaxTokensWasSet,
  normalizeSamplingPtr,
  normalizeWebSearchSettings,
  parseSettings,
  projectSettingsPath,
  type ProviderConfig,
  providerToEnvVar,
  resolveImageGenerationToken,
  resolveKey,
  resolveKeyValue,
  resolveModelConfig,
  resolveProviderConfig,
  resolveProviderHeaders,
  type ResponsesConfig,
  type RetrySettings,
  type SandboxSettings,
  sandboxSettingsOptions,
  saveGlobalSettings,
  saveGlobalSettingsPatch,
  saveProjectSettings,
  saveProjectSettingsPatch,
  setModelMaxTokens,
  type Settings,
  setVerbose,
  type SkillHubMarketSettings,
  type SkillHubSettings,
  skillsDisabled,
  type SkillsSettings,
  type StatusLineSettings,
  toolExecutionEffectiveMaxConcurrency,
  toolExecutionEffectiveMode,
  type ToolExecutionSettings,
  Verbose,
  type WebSearchSettings,
} from "./settings.ts";
export {
  applyEnvPatch,
  clearEnv,
  type EnvConfig,
  envList,
  globalEnvPath,
  loadEnv,
  saveEnv,
  setEnv,
  unsetEnv,
  validateEnvName,
} from "./env.ts";
export {
  defaultMCPConfig,
  fullMCPConfigTemplate,
  globalMCPPath,
  loadMCPConfig,
  type MCPConfig,
  type MCPKeyValue,
  type MCPServer,
  mcpServerEnabled,
  normalizeMCPConfig,
  projectMCPPath,
  saveMCPConfig,
} from "./mcp.ts";
export {
  addBashCommand,
  addBashPrefix,
  addEditPath,
  type AllowConfig,
  clearEditPaths,
  editPathList,
  getAutoEdit,
  globalAllowPath,
  globMatch,
  loadAllow,
  matchBashCommand,
  matchEditPath,
  matchGlob,
  normalizeMatchPath,
  projectAllowPath,
  removeBashCommand,
  removeBashPrefix,
  removeEditPath,
  saveGlobalAutoEdit,
  saveGlobalAutoEditValue,
  saveProject,
  setAutoEdit,
  setGlobalAutoEdit,
  setProjectAutoEdit,
} from "./allow.ts";
