// Public session surface.
//
// The schema/migrations foundation, the SQLite-backed Manager and its listing/
// deletion helpers, the Event/Run/Decision/lease projections, and the
// knowledge-base subsystems are all ported. The static architecture guards
// live in `src/architecture` (backlog item #34).

export {
  type AdditionalDirectoriesEntry,
  type BranchSummaryEntry,
  type CompactionEntry,
  type ContentOverrideEntry,
  entryAdditionalDirectories,
  type EntryBase,
  entryBranchSummary,
  entryCompaction,
  entryContentOverride,
  entryCustom,
  entryCustomMessage,
  entryLabel,
  entryMessage,
  entryModeChange,
  entryModelChange,
  entrySession,
  entrySessionInfo,
  entryThinkingChange,
  entryTurnEnd,
  entryTurnStart,
  type EntryType,
  generateID,
  type Header,
  type LabelEntry,
  type MessageEntry,
  type ModeChangeEntry,
  type ModelChangeEntry,
  type SessionInfoEntry,
  type ThinkingLevelChangeEntry,
  type TurnEndEntry,
  type TurnStartEntry,
} from "./entry.ts";
export {
  applySchemaMigrations,
  CURRENT_SCHEMA_VERSION,
  ensureKnowledgeBaseSchema,
} from "./migrations.ts";
export {
  type GeneratedArtifact,
  listGeneratedArtifacts,
  listSessionAttachments,
} from "./artifacts.ts";
export {
  type DatabaseIndexRepair,
  type DatabaseRecovery,
  openBunDatabase,
  queryRootDatabase,
  rootDatabasePath,
  takeDatabaseIndexRepairs,
  takeDatabaseRecoveries,
  writeRootDatabase,
} from "./database.ts";
export { decisionEventType, isDecisionEventType } from "./decision_events.ts";
export {
  consumeESMGuidance,
  type ESMGuidance,
  listESMGuidance,
  saveESMGuidance,
} from "./esm_guidance.ts";
export {
  type ArchivedFile,
  backupPathAvailable,
  DatabaseMoveError,
  databaseSidecarSuffixes,
  existingDatabaseFiles,
  type LeftBehindEntry,
  moveDatabaseFiles,
  resetBackupPath,
  resetDatabase,
  type ResetReport,
} from "./database_reset.ts";
export { runtimeOwnerID } from "./runtime_identity.ts";
export {
  acquireExecutionAdmission,
  acquireFork,
  acquireMutation,
  acquireMutations,
  acquireRecovery,
  bindRuntimeLeaseToExistingRun,
  bindRuntimeLeaseToRunTx,
  currentRuntimeLeaseBinding,
  leaseDirKey,
  LeaseHeartbeatScheduler,
  leaseHeartbeatSchedulers,
  lockRuntime,
  lockSessionData,
  markRuntimeLeaseBound,
  retainRuntimeLease,
  runtimeDatabaseIdentityFor,
  runtimeHeartbeatTiming,
  type RuntimeLeaseBinding,
  RuntimeLeaseBusyError,
  RuntimeLeaseGroup,
  RuntimeLeaseGuard,
  runtimeLeaseLost,
  RuntimeLeaseLostError,
  type RuntimeLeasePurpose,
  RuntimeLeasePurposeError,
  RuntimeLeaseRunMismatchError,
  RuntimeSessionNotFoundError,
  SessionRecoveryNotNeededError,
  SessionRecoveryRequiredError,
  SessionRunActiveError,
  snapshotRuntimeLeasesForDir,
  tryLockRuntime,
  tryLockRuntimes,
  validateRuntimeLease,
  validateRuntimeLeaseBindingTx,
  validateRuntimeLeaseTx,
} from "./runtime_lock.ts";
export {
  closeDatabases,
  openExistingSessionDB,
  openExistingSessionDBReadOnly,
  openRootDB,
  openStandaloneDB,
  parseSessionTimestamp,
  rootDBPath,
} from "./root_db.ts";
export {
  type Binding,
  bindSession,
  type ChannelToolConfig,
  findBinding,
  findBindingBySessionId,
  getChannelToolGeneration,
  listBindings,
  listChannelTools,
  setChannelTools,
  transferBinding,
  unbindSession,
  validateBinding,
} from "./bindings.ts";
export {
  appendInputResourceEventTx,
  bindInputResourcesToRunTx,
  type InputResourceEvent,
  listInputResourceEvents,
  saveInputResourceEvent,
} from "./input_resources.ts";
export {
  continueRecent,
  countAll,
  countWithMessages,
  createBound,
  createManager,
  createSubAgentManager,
  deleteSession,
  deleteSessionWithMutation,
  encodePath,
  findHandleForID,
  latestAdditionalDirectoriesByID,
  latestModelChangeByID,
  listAll,
  listAllDetailed,
  listForDir,
  listForDirDetailed,
  type ListOption,
  type ListOptions,
  Manager,
  openByID,
  openByIDExact,
  openByPathOrID,
  openSession,
  resolveDBPath,
  rotateBoundSession,
  type SessionDetail,
  type SessionEntry,
  sessionFileID,
  type SessionInfo,
  withLimit,
  withMessagesOnly,
  withOffset,
  withSearch,
} from "./manager.ts";
export {
  type ActiveRuntimeLease,
  activeRuntimeLeases,
  describeActiveRuntimeLease,
} from "./runtime_lease_status.ts";
export {
  getRuntimeSubmission,
  reserveRuntimeSubmissionTx,
  type RuntimeSubmission,
  RuntimeSubmissionConflictError,
  RuntimeSubmissionError,
  RuntimeSubmissionExistsError,
  type RuntimeSubmissionRunInput,
} from "./runtime_submission.ts";
export {
  createProject,
  deleteProject,
  getSessionMetadata,
  latestSessionTitle,
  listProjects,
  listSessionMetadata,
  type Project,
  projectSessionCounts,
  renameProject,
  type SessionMetadata,
  setSessionMetadata,
} from "./projects.ts";
export { createIdentityLocks, IdentityLocks } from "./identity_lock.ts";
export {
  applyCompactionEntry,
  applySequencedCompactionEntry,
  buildReplayState,
  cloneContentBlock,
  cloneMessage,
  type EntryMetadata,
  getEntryMetadata,
  lastSummarizedEntryIDLocked,
  latestCompactionLocked,
  messageContentOverrides,
  type ReplayState,
  type SequencedMessage,
} from "./replay.ts";
export {
  appendTurnEntryTx,
  type ConversationTurn,
  ConversationTurnNotOpenError,
  currentLeafTx,
  endConversationTurn,
  listConversationTurns,
  normalizeTurnStatus,
  scanConversationTurnRecord,
  startConversationTurn,
  startConversationTurnTx,
  stringPtr,
} from "./conversation_turn.ts";
export { currentVersion, MemoryStore, type Store } from "./store.ts";
export {
  latestSessionRunEventSeq,
  listSessionCapabilityEvents,
  listSessionCapabilityEventsAfter,
  listSessionCapabilityEventsWithSeq,
  listSessionMessagesAfter,
  listSessionMessagesBefore,
  listSessionMessagesLatest,
  listSessionMessagesWithSeq,
  listSessionRunEvents,
  listSessionRunEventsAfter,
  listSessionRunEventsWithSeq,
  loadSessionCapabilities,
  saveSessionCapabilities,
  saveSessionCapabilityEvent,
  saveSessionRunEvent,
  type SequencedSessionCapabilityEvent,
  type SequencedSessionRunEvent,
  type SessionCapabilities,
  type SessionCapabilityEvent,
  type SessionRunEvent,
} from "./session_events.ts";
export {
  CountedMutex,
  createLockRegistry,
  LockRegistry,
} from "./lock_registry.ts";
export { ensureCurrentSchema } from "./schema.ts";
export { normalizedRunJSON } from "./run_json.ts";
export {
  claimDeliveryOperation,
  createDeliveryPlan,
  createDeliveryPlanTx,
  defaultDeliveryLeaseMs,
  type DeliveryFailure,
  type DeliveryIntent,
  DeliveryLeaseLostError,
  type DeliveryOperation,
  DeliveryOperationAbsentError,
  DeliveryOperationBusyError,
  type DeliveryPlan,
  getDeliveryOperation,
  getDeliveryPlan,
  listDeliveryFailures,
  listDueDeliveryOperations,
  listFailedTransientDeliveryOperations,
  refreshDeliveryIntentStatus,
  reopenFailedDeliveryOperation,
  requeueDeliveryOperation,
  updateDeliveryOperation,
  updateDeliveryOperationProgress,
  validDeliveryOperationStatus,
} from "./delivery_store.ts";
export {
  appendRunAssistantMessageTx,
  appendRunUserMessageTx,
  runAssistantEntryID,
  runAssistantMessageFingerprint,
  runTerminalEventID,
  runUserEntryID,
} from "./run_user_message.ts";
export {
  allowedRunPredecessors,
  annotateSessionRunError,
  createSessionRun,
  createSessionRunAndEvent,
  finishSessionRunAndConversationTurn,
  getActiveSessionRun,
  getSessionRun,
  latestSessionRunForIntent,
  listLatestSessionRuns,
  listOrphanedSessionRuns,
  listSessionRuns,
  nextSessionRunAttempt,
  saveSessionRun,
  type SessionRun,
  updateSessionRunErrorInfo,
  updateSessionRunProgress,
  updateSessionRunStatus,
  updateSessionRunUsage,
} from "./run_store.ts";
export {
  beginSessionRunRecovery,
  convergeSessionRunRecovery,
  getSessionRunRecovery,
  markSessionRunRecoveryComplete,
  markSessionRunRecoveryDetached,
  markSessionRunRecoveryFailed,
  readSessionRunRecoveryTx,
  type SessionRunRecovery,
  type SessionRunRecoveryState,
} from "./run_recovery.ts";
export {
  readSessionExecutionFacts,
  type RuntimeLeaseSnapshot,
  type SessionExecutionFacts,
} from "./execution_facts.ts";
export {
  createExecutionIntentAndSessionRun,
  createExecutionIntentAndSessionRunEvent,
  type ExecutionIntent,
  getExecutionIntent,
  saveExecutionIntent,
} from "./execution_intent.ts";
export {
  SessionIDExistsError,
  SessionModifiedError,
} from "./session_errors.ts";
export {
  deleteKnowledgeBaseDatabase,
  knowledgeBaseDatabasePath,
  KnowledgeBaseNotFoundError,
  listKnowledgeBaseDatabaseIDs,
  queryKnowledgeBaseDatabase,
  readKnowledgeBaseDatabase,
  writeKnowledgeBaseDatabase,
} from "./knowledge_database.ts";
export {
  appendKnowledgeFileGraph,
  createKnowledgeBase,
  deleteKnowledgeBase,
  getKnowledgeBase,
  getKnowledgeSnapshot,
  KNOWLEDGE_GRAPH_SCHEMA_VERSION,
  type KnowledgeBase,
  type KnowledgeBaseSpec,
  KnowledgeBaseUnindexedError,
  type KnowledgeChunk,
  type KnowledgeEdge,
  type KnowledgeEvidence,
  type KnowledgeFile,
  type KnowledgeFileGraph,
  type KnowledgeGraphQuery,
  type KnowledgeGraphReusePlan,
  type KnowledgeGraphSnapshot,
  type KnowledgeNode,
  type KnowledgeSnapshot,
  listKnowledgeBases,
  prepareKnowledgeGraphReusePlan,
  queryKnowledgeGraph,
  reuseKnowledgeSnapshotIfFilesMatch,
  storeKnowledgeGraphSnapshot,
  updateKnowledgeBase,
  validateKnowledgeBaseSpec,
  validateKnowledgeGraphSnapshot,
} from "./knowledge_bases.ts";
export {
  ForkIdempotencyConflictError,
  ForkIdempotencyRequiredError,
  ForkIdempotencyTooLongError,
  ForkInvalidBoundaryError,
  type ForkKind,
  ForkNoCompletedTurnError,
  type ForkOptions,
  type ForkResult,
  forkSession,
  ForkSessionActiveError,
  ForkSessionNotFoundError,
  ForkUnavailableError,
  ForkUnsupportedEntryError,
} from "./fork.ts";
export {
  abandonInterruptedToolExecutionRecords,
  archiveJSON,
  claimToolExecutionRecord,
  compareAndSwapResponseSessionState,
  getResponseRun,
  getResponseSessionState,
  getResponseTurn,
  listResponseItems,
  listResponseReplayItems,
  listResponseReplayTurns,
  listResponseRuns,
  maxResponseArchiveJSONBytes,
  reclaimInterruptedToolExecution,
  requestToolExecutionRecovery,
  requestToolExecutionRecoveryRecords,
  type ResponseItemArchive,
  type ResponseReplayTurn,
  type ResponseRun,
  type ResponseSessionState,
  type ResponseTurn,
  saveResponseItem,
  saveResponseRun,
  saveResponseTurn,
  type ToolExecutionRecord,
  updateToolExecutionRecord,
} from "./response_store.ts";
export {
  isNonTerminalSessionRunStatus,
  isTerminalSessionRunStatus,
  nonTerminalSessionRunStatuses,
  nonTerminalSessionRunStatusList,
  nonTerminalSessionRunStatusSQL,
  terminalSessionRunStatuses,
  terminalSessionRunStatusList,
} from "./run_status.ts";
