// Public surface of src/provider/openai (ported from internal/provider/openai).
// Importing this module runs the provider registration, mirroring the Go
// package init().

export {
  maxResolvedAttachmentBytes,
  type OpenAIAttachmentHost,
  resolveAttachment,
  resolveAttachmentWithMetadata,
} from "./attachments.ts";
export {
  hostedRequestCapabilities,
  type HostedToolDescriptor,
  hostedToolDescriptorForType,
  hostedToolTypes,
  type ResponsesHostedPolicy,
  responsesHostedToolRegistry,
} from "./hosted_registry.ts";
export {
  applyResponsesConfig,
  applyResponsesOptions,
  archiveResponsesTurn,
  buildResponsesRequest,
  chatResponses,
  convertResponsesInput,
  convertResponsesTools,
  convertResponsesUsage,
  isHostedResponsesItemType,
  nativeResponsesReplayInput,
  parseResponsesSSE,
  responseCustomToolOutput,
  type ResponsesCompletedObject,
  type ResponsesContentBlock,
  responsesEventError,
  type ResponsesInputItem,
  responsesMessageContent,
  type ResponsesOutputItem,
  responsesPromptCacheKey,
  type ResponsesProviderHost,
  responsesReasoningEffort,
  responsesReasoningSummary,
  type ResponsesRequest,
  responsesRequestDiagnostics,
  responsesRequestHasCodeInterpreter,
  responseStateMode,
  responsesTextOption,
  responsesTextOptionFromFormat,
  type ResponsesTool,
  responsesToolChoice,
  responseStopReason,
  type ResponsesUsage,
  type ResponsesWireConfig,
  responseToolOutput,
} from "./responses.ts";
export {
  archiveBackgroundResponse,
  createResponsesRunManager,
  ResponsesRunManager,
} from "./responses_runtime.ts";
export {
  canonicalResponsesJSON,
  createResponsesNormalizer,
  decodeResponsesOutputItem,
  decodeResponsesSSE,
  errResponsesAbort,
  errResponsesComputerUseUnsupported,
  errResponsesStop,
  isKnownResponsesItemType,
  isSensitiveResponsesKey,
  isUnsupportedResponsesItemType,
  limitResponsesMetadata,
  type ProviderToolCall,
  redactResponsesValue,
  responsesArgumentsRaw,
  responsesArgumentsText,
  responsesAttachmentMetadata,
  responsesConversationID,
  responsesEventItemKey,
  responsesEventItemRaw,
  type ResponsesNormalizedResponse,
  ResponsesNormalizer,
  type ResponsesResponseItem,
  type ResponsesSSEFrame,
  responsesSSEFrames,
  responsesToolKey,
  safeResponsesAttachmentURL,
} from "./responses_codec.ts";
export {
  cloneResponsesToolExtra,
  defaultResponsesInclude,
  hostedPolicyInt,
  hostedToolType,
  mergeResponsesTools,
  modelID,
  resolveResponsesCapabilities,
  type ResponsesCapabilities,
  type ResponsesCapabilityReport,
  responsesCapabilityReport,
  responsesCodecCapabilities,
  type ResponsesConfigHost,
  responsesConfigHostedTools,
  responsesConfigTextFormat,
  responsesConfigToolChoice,
  responsesHostedItemTypes,
  responsesHostedPolicies,
  responsesHostedPoliciesWithError,
  supportsPromptCacheKey,
  supportsPromptCacheRetention,
  supportsReasoningSummary,
  supportsStore,
  supportsStrictMode,
  validateRemoteMCPServerURL,
  validateRemoteMCPServerURLEgress,
  validateRemoteMCPServerURLWithLookup,
  validateResponsesCapabilities,
  validateResponsesCapabilitiesForRequest,
  validateResponsesConfig,
  validateResponsesCustomTool,
  validateResponsesRemoteMCP,
  validateStrictResponsesSchema,
} from "./responses_config.ts";
export {
  createOpenAIProvider,
  createOpenAIProviderWithHTTPClient,
  deepseekReasoningEffort,
  defaultModels,
  doubaoSeedReasoningEffort,
  isDoubaoSeedModel,
  isMaxTokensUnsupportedResponse,
  isQwenModel,
  kimiReasoningEffort,
  maxTokensField,
  mergeOpenAIUsage,
  normalizeToolResultSequence,
  type OpenAIChatRequest,
  type OpenAIDelta,
  type OpenAIImage,
  type OpenAIMessage,
  openAIReasoningEffort,
  type OpenAIResponse,
  type OpenAITool,
  type OpenAIToolCall,
  type OpenAIUsageResponse,
  Provider,
  qwenThinkingBudget,
  supportsReasoningEffort,
  toWireChatRequest,
} from "./provider.ts";
export { convertCompat, resolveOpenAIModels } from "./register.ts";
export {
  splitPartialSuffix,
  thinkCloseTag,
  thinkOpenTag,
  ThinkSplitter,
} from "./think_split.ts";

// Side-effect import: registers "openai", "openai-chat", "openai-responses",
// and "responses".
import "./register.ts";
