// Generates the npm installer packages from the binaries in `bin/`.
//
// The layout mirrors one package per platform so a user downloads ~1 binary
// instead of every platform's: `npm/opensac-installer` is the entry package
// whose `optionalDependencies` point at the platform packages, and npm resolves
// exactly one of them for the host. Publishing the platform packages first
// keeps the entry package installable the moment it lands.
//
// Package manifests are generated, not hand-edited: `npm/packages/*` is build
// output and is git-ignored.
//
// The same generator produces both registries a release publishes to. npmjs
// takes the unscoped `opensac-installer`, while GitHub Packages only accepts a
// package inside the owner's scope, so `--scope` prefixes every generated name
// and `--out` writes the scoped tree beside the tracked `npm/` entry package
// instead of overwriting it. One generator, two registries, one platform table.

import { dirname, fromFileUrl, join, resolve } from "@std/path";
import {
  PLATFORM_TARGETS,
  platformPackageName,
  type PlatformTarget,
} from "./platforms.ts";
import { resolveBuildVersion } from "./build.ts";

/** npm package that users install. */
export const INSTALLER_NAME = "opensac-installer";

/** Repository URL recorded in every generated manifest. */
const REPOSITORY = {
  type: "git",
  url: "https://gitee.com/startvibecoding/opensac.git",
};

export interface NpmPackageJson {
  name: string;
  version: string;
  description: string;
  os?: string[];
  cpu?: string[];
  files: string[];
  license: string;
  repository: typeof REPOSITORY;
  bin?: Record<string, string>;
  scripts?: Record<string, string>;
  keywords?: string[];
  engines?: Record<string, string>;
  optionalDependencies?: Record<string, string>;
}

/** Strips the `v` prefix and any `-dirty` suffix from a build version. */
export function toPackageVersion(buildVersion: string): string {
  return buildVersion.trim()
    .replace(/^v/, "")
    .replace(/-dirty$/, "");
}

/**
 * Normalizes an npm scope to its canonical `@owner` form, accepting `owner`,
 * `@owner`, or an empty value. A malformed scope is rejected here rather than
 * becoming a package name the registry will refuse to publish.
 */
export function normalizeScope(scope?: string): string {
  const trimmed = (scope ?? "").trim();
  if (trimmed === "") return "";
  const withAt = trimmed.startsWith("@") ? trimmed : `@${trimmed}`;
  if (!/^@[a-z0-9][a-z0-9._-]*$/i.test(withAt)) {
    throw new Error(`Invalid npm scope: ${scope}`);
  }
  return withAt;
}

/** Prefixes a package name with `scope`, or returns it unchanged when unscoped. */
export function scopedName(name: string, scope?: string): string {
  const normalized = normalizeScope(scope);
  return normalized === "" ? name : `${normalized}/${name}`;
}

/** Manifest for one platform package: only the fields npm resolves on. */
export function platformPackageJson(
  target: PlatformTarget,
  version: string,
  scope?: string,
): NpmPackageJson {
  return {
    name: scopedName(
      platformPackageName(target.npmPlatform, INSTALLER_NAME),
      scope,
    ),
    version,
    description: `OpenSAC native binary for ${target.os}-${target.cpu}`,
    os: [target.os],
    cpu: [target.cpu],
    files: ["bin/"],
    license: "MIT",
    repository: REPOSITORY,
  };
}

/**
 * The entry package's platform map. Built from the packages actually present
 * on disk so `optionalDependencies` never names a package that was not built.
 */
export function optionalDependencies(
  built: readonly PlatformTarget[],
  version: string,
  scope?: string,
): Record<string, string> {
  const deps: Record<string, string> = {};
  for (const target of built) {
    deps[
      scopedName(platformPackageName(target.npmPlatform, INSTALLER_NAME), scope)
    ] = version;
  }
  return deps;
}

/** Name of the npm wrapper script the entry package links as `opensac`. */
const WRAPPER_SOURCE = "npm_installer_wrapper.js";
const WRAPPER_TARGET = "opensac";
/** Name of the postinstall banner script inside the entry package. */
const POSTINSTALL_SOURCE = "npm_postinstall.js";
/** Generated platform map the wrapper requires at runtime. */
const PLATFORM_MAP_NAME = "platforms.js";

/**
 * Source of the generated platform map the wrapper requires. It is a plain
 * CommonJS module so the wrapper needs no JSON loader and no build step.
 */
export function platformMapModule(scope?: string): string {
  const entries = PLATFORM_TARGETS.map((target) =>
    `  ${JSON.stringify(target.npmPlatform)}: ${
      JSON.stringify(
        scopedName(
          platformPackageName(target.npmPlatform, INSTALLER_NAME),
          scope,
        ),
      )
    },`
  );
  return [
    "// Generated by `make npm-packages` from scripts/platforms.ts. Do not edit.",
    "module.exports = {",
    ...entries,
    "};",
  ].join("\n");
}

/**
 * Installs the hand-written entry-package assets (the `opensac` wrapper, the
 * generated platform map it requires, and the postinstall banner) into `npm/`,
 * replacing whatever was there. These are maintained as sources in `scripts/`
 * and copied in, so the entry package can never drift from the repo's own copy
 * of the wrapper.
 */
export async function installEntryAssets(
  repoDir: string,
  npmDir = join(repoDir, "npm"),
  scope?: string,
  entryTemplate = join(repoDir, "npm", "package.json"),
): Promise<void> {
  const binDir = join(npmDir, "bin");
  await Deno.mkdir(binDir, { recursive: true });
  // Drop stale files so a renamed wrapper cannot leave a dead `opensac` link.
  for await (const entry of Deno.readDir(binDir)) {
    await Deno.remove(join(binDir, entry.name), { recursive: true });
  }

  const wrapper = join(binDir, WRAPPER_TARGET);
  await Deno.copyFile(join(repoDir, "scripts", WRAPPER_SOURCE), wrapper);
  await Deno.chmod(wrapper, 0o755);

  // The wrapper requires this map, so it is generated rather than written by
  // hand: the published wrapper can never disagree with the platform table.
  await Deno.writeTextFile(
    join(binDir, PLATFORM_MAP_NAME),
    platformMapModule(scope) + "\n",
  );

  const scriptsDir = join(npmDir, "scripts");
  await Deno.mkdir(scriptsDir, { recursive: true });
  await Deno.copyFile(
    join(repoDir, "scripts", POSTINSTALL_SOURCE),
    join(scriptsDir, "postinstall.js"),
  );

  // The entry manifest's `files` lists a README, so the generated tree gets the
  // one the template was written next to. A scoped build writes into its own
  // directory and would otherwise publish without it.
  try {
    await Deno.copyFile(
      join(dirname(entryTemplate), "README.md"),
      join(npmDir, "README.md"),
    );
  } catch {
    // No README beside the template: nothing to install, not a failure.
  }
}

/** True when the target's binary exists and is non-empty. */
async function isUsableBinary(path: string): Promise<boolean> {
  try {
    const info = await Deno.stat(path);
    return info.isFile && info.size > 0;
  } catch {
    return false;
  }
}

/** Writes a manifest as pretty-printed JSON with a trailing newline. */
async function writeManifest(path: string, pkg: NpmPackageJson): Promise<void> {
  await Deno.mkdir(dirname(path), { recursive: true });
  await Deno.writeTextFile(path, `${JSON.stringify(pkg, null, 2)}\n`);
}

/** Where a generated package tree goes, and under which npm scope. */
export interface NpmPackageOptions {
  /**
   * Output tree. Defaults to the tracked `npm/` entry package, which is then
   * rewritten in place; a different directory leaves the tracked manifest
   * alone and is what a scoped GitHub Packages build uses.
   */
  npmDir?: string;
  /** npm scope for every generated name, e.g. `@owner`. Empty = unscoped. */
  scope?: string;
  /**
   * Entry manifest used as the template for the generated entry package.
   * Defaults to the tracked `npm/package.json`.
   */
  entryTemplate?: string;
}

/**
 * Builds `<npmDir>/packages/<installer>-<platform>/` for every target whose
 * binary is present in `bin/`, and writes an entry package whose
 * `optionalDependencies` match. Returns the targets that were packaged.
 */
export async function buildNpmPackages(
  repoDir: string,
  version: string,
  options: NpmPackageOptions = {},
): Promise<PlatformTarget[]> {
  const npmDir = options.npmDir ?? join(repoDir, "npm");
  const scope = normalizeScope(options.scope);
  const entryTemplate = options.entryTemplate ??
    join(repoDir, "npm", "package.json");
  await installEntryAssets(repoDir, npmDir, scope, entryTemplate);
  const packagesDir = join(npmDir, "packages");
  // Regenerate from scratch so a removed platform cannot linger as a stale
  // package that still looks publishable.
  await Deno.remove(packagesDir, { recursive: true }).catch(() => {});

  const built: PlatformTarget[] = [];
  for (const target of PLATFORM_TARGETS) {
    const binary = join(repoDir, "bin", target.binary);
    if (!await isUsableBinary(binary)) {
      console.error(
        `Skipping ${target.npmPlatform}: bin/${target.binary} is missing or empty`,
      );
      continue;
    }
    const pkgDir = join(packagesDir, INSTALLER_NAME + "-" + target.npmPlatform);
    const innerDir = join(pkgDir, "bin");
    await Deno.mkdir(innerDir, { recursive: true });
    await Deno.copyFile(binary, join(innerDir, target.innerBinary));
    if (target.os !== "win32") {
      await Deno.chmod(join(innerDir, target.innerBinary), 0o755);
    }
    await writeManifest(
      join(pkgDir, "package.json"),
      platformPackageJson(target, version, scope),
    );
    built.push(target);
  }

  if (built.length === 0) {
    throw new Error(
      "No binaries in bin/. Run `make build-all` before building npm packages.",
    );
  }

  // The entry package is generated from the tracked manifest so a scoped build
  // keeps the same description, keywords, and `files` list as the unscoped one;
  // only the name, version, and platform map are release-specific.
  const entry = JSON.parse(
    await Deno.readTextFile(entryTemplate),
  ) as NpmPackageJson;
  entry.name = scopedName(INSTALLER_NAME, scope);
  entry.version = version;
  entry.optionalDependencies = optionalDependencies(built, version, scope);
  await writeManifest(join(npmDir, "package.json"), entry);

  return built;
}

if (import.meta.main) {
  const repoDir = resolve(dirname(fromFileUrl(import.meta.url)), "..");
  const version = toPackageVersion(await resolveBuildVersion(repoDir));
  if (version === "") {
    console.error(
      "Cannot determine a package version: no `v*` git tag and no deno.json version",
    );
    Deno.exit(1);
  }
  let options: NpmPackageOptions = {};
  for (const arg of Deno.args) {
    if (arg.startsWith("--scope=")) {
      options = { ...options, scope: normalizeScope(arg.slice(8)) };
    } else if (arg.startsWith("--out=")) {
      options = { ...options, npmDir: resolve(repoDir, arg.slice(6)) };
    } else {
      console.error(`Unknown option: ${arg}`);
      Deno.exit(1);
    }
  }
  const built = await buildNpmPackages(repoDir, version, options);
  const tree = options.npmDir ?? join(repoDir, "npm");
  console.error(
    `Built ${built.length} platform package(s) at ${version} in ${tree}: ` +
      built.map((target) => target.npmPlatform).join(", "),
  );
}
