// Generates the npm installer packages from the binaries in `bin/`.
//
// The layout mirrors one package per platform so a user downloads ~1 binary
// instead of every platform's: `npm/opensac-installer` is the entry package
// whose `optionalDependencies` point at the platform packages, and npm resolves
// exactly one of them for the host. Publishing the platform packages first
// keeps the entry package installable the moment it lands.
//
// Package manifests are generated, not hand-edited: `npm/packages/*` is build
// output and is git-ignored.

import { dirname, fromFileUrl, join, resolve } from "@std/path";
import {
  PLATFORM_TARGETS,
  platformPackageName,
  type PlatformTarget,
} from "./platforms.ts";
import { resolveBuildVersion } from "./build.ts";

/** npm package that users install. */
export const INSTALLER_NAME = "opensac-installer";

/** Repository URL recorded in every generated manifest. */
const REPOSITORY = {
  type: "git",
  url: "https://gitee.com/startvibecoding/opensac.git",
};

export interface NpmPackageJson {
  name: string;
  version: string;
  description: string;
  os?: string[];
  cpu?: string[];
  files: string[];
  license: string;
  repository: typeof REPOSITORY;
  bin?: Record<string, string>;
  scripts?: Record<string, string>;
  keywords?: string[];
  engines?: Record<string, string>;
  optionalDependencies?: Record<string, string>;
}

/** Strips the `v` prefix and any `-dirty` suffix from a build version. */
export function toPackageVersion(buildVersion: string): string {
  return buildVersion.trim()
    .replace(/^v/, "")
    .replace(/-dirty$/, "");
}

/** Manifest for one platform package: only the fields npm resolves on. */
export function platformPackageJson(
  target: PlatformTarget,
  version: string,
): NpmPackageJson {
  return {
    name: platformPackageName(target.npmPlatform, INSTALLER_NAME),
    version,
    description: `OpenSAC native binary for ${target.os}-${target.cpu}`,
    os: [target.os],
    cpu: [target.cpu],
    files: ["bin/"],
    license: "MIT",
    repository: REPOSITORY,
  };
}

/**
 * The entry package's platform map. Built from the packages actually present
 * on disk so `optionalDependencies` never names a package that was not built.
 */
export function optionalDependencies(
  built: readonly PlatformTarget[],
  version: string,
): Record<string, string> {
  const deps: Record<string, string> = {};
  for (const target of built) {
    deps[platformPackageName(target.npmPlatform, INSTALLER_NAME)] = version;
  }
  return deps;
}

/** Name of the npm wrapper script the entry package links as `opensac`. */
const WRAPPER_SOURCE = "npm_installer_wrapper.js";
const WRAPPER_TARGET = "opensac";
/** Name of the postinstall banner script inside the entry package. */
const POSTINSTALL_SOURCE = "npm_postinstall.js";
/** Generated platform map the wrapper requires at runtime. */
const PLATFORM_MAP_NAME = "platforms.js";

/**
 * Source of the generated platform map the wrapper requires. It is a plain
 * CommonJS module so the wrapper needs no JSON loader and no build step.
 */
export function platformMapModule(): string {
  const entries = PLATFORM_TARGETS.map((target) =>
    `  ${JSON.stringify(target.npmPlatform)}: ${
      JSON.stringify(platformPackageName(target.npmPlatform, INSTALLER_NAME))
    },`
  );
  return [
    "// Generated by `make npm-packages` from scripts/platforms.ts. Do not edit.",
    "module.exports = {",
    ...entries,
    "};",
  ].join("\n");
}

/**
 * Installs the hand-written entry-package assets (the `opensac` wrapper, the
 * generated platform map it requires, and the postinstall banner) into `npm/`,
 * replacing whatever was there. These are maintained as sources in `scripts/`
 * and copied in, so the entry package can never drift from the repo's own copy
 * of the wrapper.
 */
export async function installEntryAssets(
  repoDir: string,
  npmDir = join(repoDir, "npm"),
): Promise<void> {
  const binDir = join(npmDir, "bin");
  await Deno.mkdir(binDir, { recursive: true });
  // Drop stale files so a renamed wrapper cannot leave a dead `opensac` link.
  for await (const entry of Deno.readDir(binDir)) {
    await Deno.remove(join(binDir, entry.name), { recursive: true });
  }

  const wrapper = join(binDir, WRAPPER_TARGET);
  await Deno.copyFile(join(repoDir, "scripts", WRAPPER_SOURCE), wrapper);
  await Deno.chmod(wrapper, 0o755);

  // The wrapper requires this map, so it is generated rather than written by
  // hand: the published wrapper can never disagree with the platform table.
  await Deno.writeTextFile(
    join(binDir, PLATFORM_MAP_NAME),
    platformMapModule() + "\n",
  );

  const scriptsDir = join(npmDir, "scripts");
  await Deno.mkdir(scriptsDir, { recursive: true });
  await Deno.copyFile(
    join(repoDir, "scripts", POSTINSTALL_SOURCE),
    join(scriptsDir, "postinstall.js"),
  );
}

/** True when the target's binary exists and is non-empty. */
async function isUsableBinary(path: string): Promise<boolean> {
  try {
    const info = await Deno.stat(path);
    return info.isFile && info.size > 0;
  } catch {
    return false;
  }
}

/** Writes a manifest as pretty-printed JSON with a trailing newline. */
async function writeManifest(path: string, pkg: NpmPackageJson): Promise<void> {
  await Deno.mkdir(dirname(path), { recursive: true });
  await Deno.writeTextFile(path, `${JSON.stringify(pkg, null, 2)}\n`);
}

/**
 * Builds `npm/packages/<name>/` for every target whose binary is present in
 * `bin/`, and rewrites the entry package's `optionalDependencies` to match.
 * Returns the targets that were packaged.
 */
export async function buildNpmPackages(
  repoDir: string,
  version: string,
  npmDir = join(repoDir, "npm"),
): Promise<PlatformTarget[]> {
  await installEntryAssets(repoDir, npmDir);
  const packagesDir = join(npmDir, "packages");
  // Regenerate from scratch so a removed platform cannot linger as a stale
  // package that still looks publishable.
  await Deno.remove(packagesDir, { recursive: true }).catch(() => {});

  const built: PlatformTarget[] = [];
  for (const target of PLATFORM_TARGETS) {
    const binary = join(repoDir, "bin", target.binary);
    if (!await isUsableBinary(binary)) {
      console.error(
        `Skipping ${target.npmPlatform}: bin/${target.binary} is missing or empty`,
      );
      continue;
    }
    const pkgDir = join(packagesDir, INSTALLER_NAME + "-" + target.npmPlatform);
    const innerDir = join(pkgDir, "bin");
    await Deno.mkdir(innerDir, { recursive: true });
    await Deno.copyFile(binary, join(innerDir, target.innerBinary));
    if (target.os !== "win32") {
      await Deno.chmod(join(innerDir, target.innerBinary), 0o755);
    }
    await writeManifest(
      join(pkgDir, "package.json"),
      platformPackageJson(target, version),
    );
    built.push(target);
  }

  if (built.length === 0) {
    throw new Error(
      "No binaries in bin/. Run `make build-all` before building npm packages.",
    );
  }

  const entryManifest = join(npmDir, "package.json");
  const entry = JSON.parse(
    await Deno.readTextFile(entryManifest),
  ) as NpmPackageJson;
  entry.version = version;
  entry.optionalDependencies = optionalDependencies(built, version);
  await writeManifest(entryManifest, entry);

  return built;
}

if (import.meta.main) {
  const repoDir = resolve(dirname(fromFileUrl(import.meta.url)), "..");
  const version = toPackageVersion(await resolveBuildVersion(repoDir));
  if (version === "") {
    console.error(
      "Cannot determine a package version: no `v*` git tag and no deno.json version",
    );
    Deno.exit(1);
  }
  const built = await buildNpmPackages(repoDir, version);
  console.error(
    `Built ${built.length} platform package(s) at ${version}: ` +
      built.map((target) => target.npmPlatform).join(", "),
  );
}
